replicaCount: 1

image:
  repository: teju792/products-appimg
  pullPolicy: IfNotPresent
  tag: "tag1.1"

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 3002

ingress:
  enabled: true
  className: ""
  annotations: 
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: products.appdevops.work.gd
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
   - secretName: mytls-secret
     hosts:
       - products.appdevops.work.gd

env:
  PORT: "3002" # Make sure to enclose the value in quotes
  PRODUCT_SERVICE_URL: "http://product-service1-productservicehelm:3001"

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
